# Generated by Django 4.2 on 2023-10-20 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicationform',
            name='countrycode',
            field=models.CharField(blank=True, choices=[('+91', '+91'), ('+7', '+7')], default='+91', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplicationform',
            name='country',
            field=models.CharField(blank=True, default='Unknown', max_length=50, null=True),
        ),
    ]
