# Generated by Django 4.2 on 2023-10-21 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_jobapplicationform_countrycode_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobApplicationForm',
            new_name='JobApplicationModel',
        ),
    ]
