# Generated by Django 4.2.6 on 2023-10-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience_type',
            field=models.CharField(choices=[('0-1 years', '0-1 years'), ('1-2 years', '1-2 years'), ('2-4 years', '2-4 years'), ('4-5years', '4-5 years'), ('5+ years', '5+ years')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('software engineer', 'Software Engineer'), ('teacher', 'Teacher'), ('driver', 'Driver'), ('data analyst', 'Data Analyst'), ('cloud engineer', 'Cloud Engineer')], max_length=50),
        ),
    ]
