# Generated by Django 3.2.12 on 2023-10-17 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp1', '0003_alter_job_experience_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='countrycode',
            field=models.CharField(blank=True, choices=[('+91', 'India'), ('+71', 'America')], default='DEFAULT VALUE', max_length=3, null=True),
        ),
    ]
